# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 前端小哥郭明霞的小天地
# email: baokang325@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  分享技术、结交天下朋友是我毕生的追求。像王守仁一样“格”物。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gmx101010.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
google_analytics: UA-208608166-1

# Disqus Comments 虽有广告，但无评论不博客
# disqus:
#     # Leave shortname blank to disable comments site-wide.
#     # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
#     shortname: kangear

#google:
#  ad-client: "ca-pub-5984522345984184"
#  ad-slot: "9439014959"

# 搜索
# webmaster_verifications:
#   google: I515YPtISI31CKCXQ-I3amwWFSS8KyQcvhA8oZtT6Ps
  # bing: 1234
  # alexa: 1234
  # yandex: 1234
  # baidu: 1234

# 类别
jekyll-archives:
  enabled: all
  layouts:
    year: archive/year
    month: archive/month
    day: archive/day
    tag: archive/tag
    category: archive/category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tags/:name/'
    category: '/category/:name/'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
